import { createElement } from "@lwc/engine-dom";
import duplicateMasterPreview from "c/duplicationMasterPreview";
import { describe, it, expect, afterEach } from "@testing-library/dom";

describe("c-duplicate-master-preview", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-duplicate-master-preview", {
      is: duplicateMasterPreview
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
