name: Deploy to Development Sandbox

on:
  push:
    branches: [main]
    paths:
      - "force-app/**"
  # Add manual trigger for deploying from any branch
  workflow_dispatch:
    inputs:
      comments:
        description: "Deployment comments"
        required: true
        default: "Manual development sandbox deployment"

jobs:
  deploy-to-sandbox:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      # Use Username/Password authentication
      - name: Authenticate to Salesforce
        run: |
          # First, try using the SFDX auth URL if it exists
          if [ -n "${{ secrets.SFDX_AUTH_URL }}" ]; then
            echo "${{ secrets.SFDX_AUTH_URL }}" > ./SFDX_AUTH_URL.txt
            sf org login sfdx-url --sfdx-url-file ./SFDX_AUTH_URL.txt -a dupesandbox
          else
            # Fall back to username/password (more common)
            sf org login web -a dupesandbox -r https://test.salesforce.com
            echo "Manual authentication required in browser"
            echo "::warning::Using web-based authentication. For CI automation, add SFDX_AUTH_URL secret!"
          fi

      # First validate the deployment
      - name: Validate Sandbox Deployment
        run: |
          sf project deploy validate --source-dir force-app --target-org dupesandbox --test-level RunLocalTests

      # Then do the actual deployment
      - name: Deploy to Sandbox
        run: |
          sf project deploy start --source-dir force-app --target-org dupesandbox --test-level RunLocalTests

      - name: Run Apex Tests
        run: |
          mkdir -p test-results
          sf apex run test --target-org dupesandbox --code-coverage --result-format junit --output-dir ./test-results

      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results

      - name: Post-Deployment Summary
        run: |
          echo "Deployment to development sandbox completed successfully"
          echo "Deployed by: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"
          echo "Comments: ${{ github.event.inputs.comments || 'Automated deployment from branch' }}"
